expenses-report-print.css: expenses-report-print.scss _reboot.scss _variables.scss
	sass expenses-report-print.scss > expenses-report-print.css
	cp expenses-report-print.css ../expenses/static/expenses/
