# Generated by Django 2.1.1 on 2018-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.CharField(max_length=40, verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='billitemtemplate',
            name='product',
            field=models.CharField(max_length=40, verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=80, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='description',
            field=models.CharField(max_length=80, verbose_name='description (!count! tag accepted)'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='vendor',
            field=models.CharField(max_length=40, verbose_name='vendor'),
        ),
    ]
