# Generated by Django 2.1.1 on 2018-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_shorter_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(max_length=40, verbose_name='vendor'),
        ),
    ]
