# Generated by Django 2.1.2 on 2018-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_delete_billitemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetemplate',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='name'),
            preserve_default=False,
        ),
    ]
