# Generated by Django 2.1.2 on 2018-10-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensetemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetemplate',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
