# Generated by Django 2.1.2 on 2018-10-28 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expensetemplate_type_defaults_to_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.CharField(max_length=40, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='serving',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Serving [g, L]'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=20, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slugbase',
            field=models.CharField(max_length=20, verbose_name='Slug base'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=80, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_bill',
            field=models.BooleanField(default=False, verbose_name='This is a bill'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(max_length=40, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Description (!count! tag accepted)'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('count', 'Multiplied by count')], default='simple', max_length=20, verbose_name='Template type'),
        ),
        migrations.AlterField(
            model_name='expensetemplate',
            name='vendor',
            field=models.CharField(max_length=40, verbose_name='Vendor'),
        ),
    ]
