# Generated by Django 2.1.2 on 2019-02-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_deletionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetemplate',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
    ]
