# Generated by Django 2.1.5 on 2019-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_long_template_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'user'], name='expenses_ca_slug_f16aab_idx'),
        ),
    ]
