# Generated by Django 2.1.2 on 2019-02-09 17:46

from django.db import migrations, models


def generate_cached_descriptions(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    for expense in Expense.objects.filter(is_bill=True):
        if expense.billitem_set.count() != 0:
            expense.description_cache = ", ".join(i.product for i in expense.billitem_set.all())
            expense.save()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_category_slug_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description_cache',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description (cache)'),
        ),
        migrations.RunPython(generate_cached_descriptions),
    ]
