# Generated by Django 2.2.3 on 2019-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_desc_select_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetemplate',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('count', 'Multiplied by count'), ('description', 'With custom description'), ('desc_select', 'With description selected from list'), ('menu', 'Menu (amount and description selected from list)')], default='simple', max_length=20, verbose_name='Template type'),
        ),
    ]
