# Generated by Django 6.0.3 on 2026-03-06 09:41

import builtins
from django.db import migrations, models
from expenses.utils import asciify


def populate_ascii_fields(apps, schema_editor):
    BillItem = apps.get_model('expenses', 'BillItem')
    Expense = apps.get_model('expenses', 'Expense')

    for item in BillItem.objects.all():
        item.product_ascii = asciify(item.product)
        item.save(update_fields=['product_ascii'])

    for expense in Expense.objects.all():
        expense.description_ascii = asciify(expense.description) if expense.description else ''
        expense.vendor_ascii = asciify(expense.vendor)
        expense.save(update_fields=['description_ascii', 'vendor_ascii'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='product_ascii',
            field=models.CharField(default='', max_length=40, verbose_name='Product (ASCII)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description_ascii',
            field=models.CharField(blank=True, max_length=80, verbose_name='Description (ASCII)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_ascii',
            field=models.CharField(default='', max_length=40, verbose_name='Vendor (ASCII)'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_ascii_fields, reverse_populate),
    ]
