# Generated by Django 6.0.3 on 2026-03-06 20:01
# Redo asciify after casefold was added

import builtins
from django.db import migrations, models
from expenses.utils import asciify


def populate_ascii_fields(apps, schema_editor):
    BillItem = apps.get_model('expenses', 'BillItem')
    Expense = apps.get_model('expenses', 'Expense')

    for item in BillItem.objects.all():
        item.product_ascii = asciify(item.product)
        item.save(update_fields=['product_ascii'])

    for expense in Expense.objects.all():
        expense.description_ascii = asciify(expense.description) if expense.description else ''
        expense.vendor_ascii = asciify(expense.vendor)
        expense.save(update_fields=['description_ascii', 'vendor_ascii'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_ascii'),
    ]

    operations = [
        migrations.RunPython(populate_ascii_fields, reverse_populate),
    ]
